### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by lucasub** [odoo/wkhtmltopdf#4]
Please, can you write well how to build wkhtmltopdf ? I can try with debian 12.0 but now work. 

Thank you
Luca

**Comment by ghost** [comment]
Check if you have all the required [dependencies](https://github.com/odoo/wkhtmltopdf/blob/master/meta/data/pod-debian-bookworm.json) installed on your system, then simply follow the instruction presented on the [README](https://github.com/odoo/wkhtmltopdf/blob/master/meta/data/pod-debian-bookworm.json).

If you have any issue feel free to ask.

**Comment by rafaeldev** [comment]
Hi!

Do you have any plan to build for arm64 arch?
I tried build on my Mac M1 but I can't

**Comment by ghost** [comment]
Closed for inactivity
