### ISSUE TITLE
fix: Support for multiple documents

### ISSUE THREAD

**Issue by ryshu** [odoo/wkhtmltopdf#5]
Hi,

When trying to build multiples documents with this version, i'm getting following output:

```
wkhtmltopdf: Error: This version of wkhtmltopdf is built against an unpatched version of QT, and does not support more than one input document.
```

Is this possible to have a version with patched QT ?

Regards

**Comment by sleepy-monax** [comment]
It's always built with the patched QT; some code slipped when I removed all the code related to the unpatched version.  It's fixed now by a976daa5e5f9c03fec8b19f1fadd508b10c80f21
